In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [2]:
!ls ../data

AMZN.csv           apply_demo.csv     iris.csv           top5.csv
BABA.csv           city_weather.csv   movie_metadata.csv train.csv
Pokemon.csv        demo_duplicate.csv sales-funnel.xlsx  usa_flights.csv

In [3]:
df = pd.read_csv('../data/movie_metadata.csv')

In [4]:
df.shape

(5043, 28)

# Head and tail

In [7]:
df.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000

In [9]:
df.tail(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
5034,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
5036,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

# filter columns

In [14]:
df[['director_name','movie_title']]

           director_name                                        movie_title
0          James Cameron                                            Avatar
1         Gore Verbinski          Pirates of the Caribbean: At World's End
2             Sam Mendes                                           Spectre
3      Christopher Nolan                             The Dark Knight Rises
4            Doug Walker  Star Wars: Episode VII - The Force Awakens    ...
5         Andrew Stanton                                       John Carter
6              Sam Raimi                                      Spider-Man 3
7           Nathan Greno                                           Tangled
8            Joss Whedon                           Avengers: Age of Ultron
9            David Yates            Harry Potter and the Half-Blood Prince
10           Zack Snyder                Batman v Superman: Dawn of Justice
11          Bryan Singer                                  Superman Returns
12          Marc Forster                                 Quantum of Solace
13        Gore Verbinski        Pirates of the Caribbean: Dead Man's Chest
14        Gore Verbinski                                   The Lone Ranger
15           Zack Snyder                                      Man of Steel
16        Andrew Adamson          The Chronicles of Narnia: Prince Caspian
17           Joss Whedon                                      The Avengers
18          Rob Marshall       Pirates of the Caribbean: On Stranger Tides
19      Barry Sonnenfeld                                    Men in Black 3
20         Peter Jackson         The Hobbit: The Battle of the Five Armies
21             Marc Webb                            The Amazing Spider-Man
22          Ridley Scott                                        Robin Hood
23         Peter Jackson               The Hobbit: The Desolation of Smaug
24           Chris Weitz                                The Golden Compass
25         Peter Jackson                                         King Kong
26         James Cameron                                           Titanic
27         Anthony Russo                        Captain America: Civil War
28            Peter Berg                                        Battleship
29       Colin Trevorrow                                    Jurassic World
...                  ...                                                ...
5013          Eric Eason                                            Manito
5014            Uwe Boll                                           Rampage
5015   Richard Linklater                                           Slacker
5016     Joseph Mazzella                                       Dutch Kills
5017        Travis Legge                                         Dry Spell
5018       Alex Kendrick                                          Flywheel
5019       Marcus Nispel                                            Exeter
5020     Brandon Landers                                        The Ridges
5021         Jay Duplass                                   The Puffy Chair
5022          Jim Chuchu                              Stories of Our Lives
5023          Daryl Wein                                  Breaking Upwards
5024         Jason Trost                          All Superheroes Must Die
5025         John Waters                                    Pink Flamingos
5026     Olivier Assayas                                             Clean
5027        Jafar Panahi                                        The Circle
5028       Ivan Kavanagh                                       Tin Can Man
5029    Kiyoshi Kurosawa                                          The Cure
5030        Tadeo Garcia                                    On the Downlow
5031  Thomas L. Phillips                      Sanctuary; Quite a Conundrum
5032     Ash Baron-Cohen                                              Bang
5033       Shane Carruth                                            Primer
5034    Neill Dela Llana                                            Cavite
5035    Robert Rodriguez                                       El Mariachi
5036     Anthony Vallone                                   The Mongol King
5037        Edward Burns                                         Newlyweds
5038         Scott Smith                           Signed Sealed Delivered
5039                 NaN                         The Following
5040    Benjamin Roberds                              A Plague So Pleasant
5041         Daniel Hsia                                  Shanghai Calling
5042            Jon Gunn                                 My Date with Drew

[5043 rows x 2 columns]

In [11]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

# filter by position

In [20]:
df.iloc[0].values

array(['Color', 'James Cameron', 723.0, 178.0, 0.0, 855.0,
       'Joel David Moore', 1000.0, 760505847.0,
       'Action|Adventure|Fantasy|Sci-Fi', 'CCH Pounder', 'Avatar\xa0',
       886204, 4834, 'Wes Studi', 0.0,
       'avatar|future|marine|native|paraplegic',
       'http://www.imdb.com/title/tt0499549/?ref_=fn_tt_tt_1', 3054.0,
       'English', 'USA', 'PG-13', 237000000.0, 2009.0, 936.0,
       7.9000000000000004, 1.78, 33000], dtype=object)

In [17]:
df.head(1)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000

In [26]:
df.iloc[1:10,0:2]

   color      director_name
1  Color     Gore Verbinski
2  Color         Sam Mendes
3  Color  Christopher Nolan
4    NaN        Doug Walker
5  Color     Andrew Stanton
6  Color          Sam Raimi
7  Color       Nathan Greno
8  Color        Joss Whedon
9  Color        David Yates

# filter by label

In [31]:
df.loc[[1,4],['director_name','movie_title']]

    director_name                                        movie_title
1  Gore Verbinski          Pirates of the Caribbean: At World's End
4     Doug Walker  Star Wars: Episode VII - The Force Awakens    ...